Login/urls.py
from django.conf.urls import url
from .views import index, logout_view,login_view

app_name = 'Login'

urlpatterns = [
    url(r'^$', index, name='login'),
    url(r'^validate/$', login_view, name='validate'),
    url(r'^logout/$', logout_view, name='logout')]

User/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LogoutView
#LoginView,
from django.conf.urls import url
from . import views

app_name = "user"

urlpatterns = [
    path('register', views.register, name="register"),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', views.view_profile, name="view_profile")
]

donasi_sosial/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur'),
]

donavid/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings
from Login.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')), 
    path('home/', homepage, name="homepage"),
    path('user/', include("User.urls", namespace="user")),
    path('login/', include(('Login.urls', 'login'), namespace='login')),
    path('testimoni/', include('testimoni.urls')),
    path('donasi-sosial/', include('donasi_sosial.urls')),
    path('formulir_donasi/', include('formulir_donasi_sosial.urls')),
    path('formulir_donasi_apd/', include('formulir_donasi_apd.urls')),
    path('donasi-apd/', include('donasi_apd.urls')),
    path('about-us/', include('about_us.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

donasi_sosial/models.py
from django.db import models
from formulir_donasi_sosial.models import Donasi

# Create your models here.
class Program(models.Model):
    name   = models.CharField(max_length=200)
    photo  = models.ImageField(upload_to="static/img")
    desc   = models.TextField()
    target = models.IntegerField()
    remDay = models.IntegerField()
    donatur = models.ManyToManyField(Donasi, blank=True)

donasi_sosial/views.py
from django.shortcuts import render, redirect
from .models import Program

# Create your views here.

def list_program(request):
    programs = Program.objects.all()
    response = {'programs': programs}
    return render(request, 'donasi.html', response)


def list_donatur(request, program):
    donasi_terkumpul = Program.objects.get(pk=program)
    nama_program = Program.objects.get(pk=program).name
    response = {
        'donasi_terkumpul': donasi_terkumpul,
        'nama_program' : nama_program,
        }
    return render(request, 'list_donatur.html', response)

donasi_sosial/templates/donasi.html
{% extends "base.html" %}
{% load static %}

{% block headone %}
<title>Donasi Sosial</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/donasi_sosial.css' %}">
{% endblock %}


{% block content %}

<!-- HEADER -->
<div id="gambar-atas">
    <p class="judul">Donasi Sosial</p>
    <p class="deskripsiJudul">Make a better life by helping each other</p>
    <a href="/donasi-sosial/#program-donasi" style="padding-bottom: 50px; " class="center">
        <button type="submit" class="btn rounded-pill" style="background-color: #772E25; color: #ffffff;">Mulai
            Berdonasi!</button>
    </a>
</div>

<!-- PROGRAM DONASI -->
<div class="container-fluid" id="program_donasi">

    <div id="program-donasi">
        <p class="judulProgramDonasi">Program Donasi</p>

        <div class="row ">
            {% if programs %}
            {% for program in programs %}

            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="card">
                    <img class="card-img-top" src='/{{ program.photo }}'>
                    <div class="card-body">
                        <h5 class="card-title">{{ program.name }}</h5>

                        <p class="card-text">Sisa hari: {{ program.remDay }} hari lagi <br> Target   : Rp.{{ program.target }}</p>

                        {%if user.is_authenticated%}

                        <div class="center">
                            <a href="{% url 'formulir_donasi' program=program.pk %}" class="btn rounded-pill btn-donasi"
                                style="">Donasi</a>
                            <a href="{% url 'programs:list_donatur' program=program.pk%}"
                                class="btn rounded-pill btn-donasi" style="">Lihat Donatur</a>
                        </div>

                        {% else %}

                        <div class="center" style="margin-top: 30px;">
                            <p style="font-size: 10px;">Ingin berdonasi? Silakan Login/Register terlebih dahulu</p>
                        </div>

                        <div class="center">
                            <a href="{% url 'Login:login' %}" class="btn rounded-pill btn-donasi"
                                style="">Login</a>
                            <a href="{% url 'user:register' %}"
                                class="btn rounded-pill btn-donasi" style="">Register</a>
                        </div>

                        <div class="center">
                            <a href="{% url 'programs:list_donatur' program=program.pk%}" class="btn rounded-pill "
                                style="background-color: #ffffff; color: #772E25; text-decoration: underline;">List Donatur</a>
                        </div>




                        {% endif %}

                    </div>
                </div>
            </div>

            {% endfor %}

            {% else %}
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <h4 class="w3-left-align" style="color: #772E25"><strong>Tidak ada program</strong></h4>
                    </div>
                </div>
            </div>
            {% endif %}

        </div>
        <br>
            <p>Coming soon...</p>
    </div>

    <div class="row content">
        <!-- FORMULIR DONASI -->
        <div class="col-md-6 ">
            <p class="teks2"> <span class="sepan">Hai, #OrangOrangBaik!</span>  <br> Terima kasih atas Donasi yang Anda keluarkan! Donasi tersebut sangat berguna bagi pemulihan COVID-19 yang ada di Indonesia. Dengan #Donavid Indonesia pasti bisa lalui Pandemi Ini!</p>
        </div>
        <!-- FOTO DONASI -->
        <div class="col-md-6 center order-1 order-md-2">
            <img class="fotoDetailDonasi" src='../static/img/bottomanimation.png'>
        </div>
    </div>

</div>

{% endblock %}

donasi_sosial/templates/list_donatur.html
{% extends "base.html" %}
{% load static %}

{% block headone %}
<title>Donasi Sosial</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/donasi_sosial.css' %}">
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-12">

            <div></div>
            <h1 class="judulListDonatur center"> Donasi Terkumpul</h1>
            <h6 class="center namaProgramListDonatur">{{ nama_program}}</h6>

            
                <div class="container">
                    {% if donasi_terkumpul.donatur.all.count == 0 %}
                    <h3 class="belum-ada center">Belum ada donasi terkumpul</h3>
                    {% else %}
                    <table class="table table-striped table-bordered" style="text-align: center;">
                        <thead>
                            <tr>
                                <th scope="col" >Nama Donatur </th>
                                <th scope="col"class="one" >Email </th>
                                <th scope="col">Donasi Terkumpul</th>
                            </tr>
                        </thead>

                        {% for data in donasi_terkumpul.donatur.all %}
                        {% if data == donasi_terkumpul.donatur.last %}
                        <tr>
                            <td scope="row">{{ data.nama }}</td>
                            <td scope="row" class="one">{{ data.email }}</td>
                            <td scope="row">{{ data.jmldonasi }}</td>
                        </tr>
                        {% else %}
                        <tr>
                            <td scope="row">{{ data.nama }}</td>
                            <td scope="row" class="one">{{ data.email }}</td>
                            <td scope="row">{{ data.jmldonasi }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                    {% endif %}
                </div>
            <br>

            <div class="center">
                <a href="/donasi-sosial/#program-donasi" class="btn rounded-pill btn-donasi center btn-kembali" style="">Kembali</a>
            </div>

        </div>

    </div>
</div>
<div style="height: 50px;"></div>
{% endblock %}